// <auto-generated />
namespace Locadora.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Refactoring4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactoring4));
        
        string IMigrationMetadata.Id
        {
            get { return "201511112345118_Refactoring 4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
